import '../models/high_tech_node_definition.dart';

const List<HighTechNodeDefinition> highTechDefinitions = [
  HighTechNodeDefinition(
    id: 'manage_food_1',
    name: 'Manage Food I',
    description: 'Reduces Food costs for Building.',
    assetPath: 'assets/images/high_tech/manage_food_1.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'manage_wood_1',
    name: 'Manage Wood I',
    description: 'Reduces Wood costs for Building.',
    assetPath: 'assets/images/high_tech/manage_wood_1.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'manage_stone_1',
    name: 'Manage Stone I',
    description: 'Reduces Stone costs for Building.',
    assetPath: 'assets/images/high_tech/manage_stone_1.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'manage_iron_1',
    name: 'Manage Iron I',
    description: 'Reduces Iron costs for Building.',
    assetPath: 'assets/images/high_tech/manage_iron_1.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'superior_leadership_1',
    name: 'Superior Leadership I',
    description: 'Increases the limit of the Marching Army.',
    assetPath: 'assets/images/high_tech/superior_leadership_1.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'melee_attack_1',
    name: 'Melee Attack I',
    description: 'Increases the Attack of Infantry and Cavalry.',
    assetPath: 'assets/images/high_tech/mele_attack_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'ranged_attack_1',
    name: 'Ranged Attack I',
    description: 'Increases the Attack of Mages and Archers.',
    assetPath: 'assets/images/high_tech/ranged_attack_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'melee_hp_1',
    name: 'Melee HP I',
    description: 'Increases the HP of Infantry and Cavalry.',
    assetPath: 'assets/images/high_tech/mele_hp_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'ranged_hp_1',
    name: 'Ranged HP I',
    description: 'Increases the HP of Mages and Archers.',
    assetPath: 'assets/images/high_tech/ranged_hp_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'superior_angel_attack_1',
    name: 'Superior Angel Attack I',
    description: 'Increases the Attack of Angels.',
    assetPath: 'assets/images/high_tech/superior_angel_attack_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'superior_angel_hp_1',
    name: 'Superior Angel HP I',
    description: 'Increases the HP of Angels.',
    assetPath: 'assets/images/high_tech/superior_angel_hp_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'elite_blade_1',
    name: 'Elite Blade I',
    description: 'Increases Damage of Troops during Elite War.',
    assetPath: 'assets/images/high_tech/elite_blade_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'invasion_blade_1',
    name: 'Invasion Blade I',
    description: 'Increases Damage of Troops during Realm Invasion.',
    assetPath: 'assets/images/high_tech/invasion_blade_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'elite_shield_1',
    name: 'Elite Shield I',
    description: 'Reduces Damage taken by Troops during Elite War.',
    assetPath: 'assets/images/high_tech/elite_shield_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'invasion_shield_1',
    name: 'Invasion Shield I',
    description: 'Reduces Damage taken by Troops during Realm Invasion.',
    assetPath: 'assets/images/high_tech/invasion_shield_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'rally_decree_1',
    name: 'Rally Decree I',
    description: 'Increases the limit of Rally Troops.',
    assetPath: 'assets/images/high_tech/rally_decree_1.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'manage_food_2',
    name: 'Manage Food II',
    description: 'Reduces Food costs for Building.',
    assetPath: 'assets/images/high_tech/manage_food_2.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'manage_wood_2',
    name: 'Manage Wood II',
    description: 'Reduces Wood costs for Building.',
    assetPath: 'assets/images/high_tech/manage_wood_2.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'manage_stone_2',
    name: 'Manage Stone II',
    description: 'Reduces Stone costs for Building.',
    assetPath: 'assets/images/high_tech/manage_stone_2.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'manage_iron_2',
    name: 'Manage Iron II',
    description: 'Reduces Iron costs for Building.',
    assetPath: 'assets/images/high_tech/manage_iron_2.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'superior_leadership_2',
    name: 'Superior Leadership II',
    description: 'Increases the limit of the Marching Army.',
    assetPath: 'assets/images/high_tech/superior_leadership_2.png',
    minLevel: 0,
    maxLevel: 5,
  ),
  HighTechNodeDefinition(
    id: 'melee_attack_2',
    name: 'Melee Attack II',
    description: 'Increases the Attack of Infantry and Cavalry.',
    assetPath: 'assets/images/high_tech/mele_attack_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'ranged_attack_2',
    name: 'Ranged Attack II',
    description: 'Increases the Attack of Mages and Archers.',
    assetPath: 'assets/images/high_tech/ranged_attack_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'melee_hp_2',
    name: 'Melee HP II',
    description: 'Increases the HP of Infantry and Cavalry.',
    assetPath: 'assets/images/high_tech/mele_hp_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'ranged_hp_2',
    name: 'Ranged HP II',
    description: 'Increases the HP of Mages and Archers.',
    assetPath: 'assets/images/high_tech/ranged_hp_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'superior_angel_attack_2',
    name: 'Superior Angel Attack II',
    description: 'Increases the Attack of Angels.',
    assetPath: 'assets/images/high_tech/superior_angel_attack_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'superior_angel_hp_2',
    name: 'Superior Angel HP II',
    description: 'Increases the HP of Angels.',
    assetPath: 'assets/images/high_tech/superior_angel_hp_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'elite_blade_2',
    name: 'Elite Blade II',
    description: 'Increases Damage of Troops during Elite War.',
    assetPath: 'assets/images/high_tech/elite_blade_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'invasion_blade_2',
    name: 'Invasion Blade II',
    description: 'Increases Damage of Troops during Realm Invasion.',
    assetPath: 'assets/images/high_tech/invasion_blade_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'elite_shield_2',
    name: 'Elite Shield II',
    description: 'Reduces Damage taken by Troops during Elite War.',
    assetPath: 'assets/images/high_tech/elite_shield_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
  HighTechNodeDefinition(
    id: 'invasion_shield_2',
    name: 'Invasion Shield II',
    description: 'Reduces Damage taken by Troops during Realm Invasion.',
    assetPath: 'assets/images/high_tech/invasion_shield_2.png',
    minLevel: 0,
    maxLevel: 10,
  ),
];

HighTechNodeDefinition highTechDefinitionFor(String nodeId) {
  return highTechDefinitions.firstWhere(
    (definition) => definition.id == nodeId,
    orElse: () =>
        throw StateError('No High Tech definition found for node: $nodeId'),
  );
}
