import '../models/artifact_category.dart';
import '../models/artifact_item_definition.dart';
import '../models/artifact_rarity.dart';

const artifactDefinitions = <ArtifactItemDefinition>[
  // Blue Artifacts — maximum 4 stars, level 30.
  ArtifactItemDefinition(
    id: 'aspis',
    name: 'Aspis',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.blue,
    assetFileName: 'aspis.png',
    starEffects: [
      'Infantry Attack',
      'Infantry HP',
      'Mage Attack',
      'Infantry Damage Reduction',
    ],
  ),
  ArtifactItemDefinition(
    id: 'book_of_thoth',
    name: 'Book of Thoth',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.blue,
    assetFileName: 'book_of_thoth.png',
    starEffects: [
      'Depot Capacity',
      'Research Speed',
      'Building Speed',
      'Troops HP',
    ],
  ),
  ArtifactItemDefinition(
    id: 'boots_of_speed',
    name: 'Boots of Speed',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.blue,
    assetFileName: 'boots_of_speed.png',
    starEffects: [
      'March Speed',
      'Monster Attack Speed',
      'Recruitment Speed',
      'Stamina Recovery',
    ],
  ),
  ArtifactItemDefinition(
    id: 'chu_ko_nu',
    name: 'Chu-Ko-Nu',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.blue,
    assetFileName: 'chu_ko_nu.png',
    starEffects: ['Archer Attack', 'Archer Damage', 'Archer HP', 'Infantry HP'],
  ),
  ArtifactItemDefinition(
    id: 'draconite',
    name: 'Draconite',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.blue,
    assetFileName: 'draconite.png',
    starEffects: [
      'Maximum Wounded',
      'Building Speed',
      'Healing Speed',
      'Troops Attack',
    ],
  ),
  ArtifactItemDefinition(
    id: 'lubu',
    name: "Lubu's Halberd",
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.blue,
    assetFileName: 'lubu.png',
    starEffects: [
      'Cavalry Attack',
      'Cavalry HP',
      'Archer Attack',
      'Cavalry Damage Reduction',
    ],
  ),
  ArtifactItemDefinition(
    id: 'muramasa',
    name: 'Muramasa',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.blue,
    assetFileName: 'muramasa.png',
    starEffects: ['Mage Attack', 'Mage HP', 'Cavalry HP', 'Mage Damage'],
  ),

  // Purple Artifacts — maximum 5 stars, level 40.
  ArtifactItemDefinition(
    id: 'curtana',
    name: 'Curtana',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.purple,
    assetFileName: 'curtana.png',
    starEffects: [
      'Damage Against Infantry',
      'Mage Attack',
      'Mage HP',
      'Cavalry Attack',
      'Troops Attack',
    ],
  ),
  ArtifactItemDefinition(
    id: 'draupnir',
    name: 'Draupnir',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.purple,
    assetFileName: 'draupnir.png',
    starEffects: [
      'Reduced Wood Building Cost',
      'Reduced Food Building Cost',
      'Depot Capacity',
      'Reduced Stone Building Cost',
      'Maximum Wounded',
    ],
  ),
  ArtifactItemDefinition(
    id: 'durendal',
    name: 'Durendal',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.purple,
    assetFileName: 'durendal.png',
    starEffects: [
      'Damage Against Cavalry',
      'Archer Attack',
      'Archer HP',
      'Infantry Attack',
      'Troops Attack',
    ],
  ),
  ArtifactItemDefinition(
    id: 'feather_dress',
    name: 'Feather Dress',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.purple,
    assetFileName: 'feather_dress.png',
    starEffects: [
      'Reduced Damage Taken from Archers',
      'Infantry HP',
      'Infantry Attack',
      'Archer HP',
      'Troops HP',
    ],
  ),
  ArtifactItemDefinition(
    id: 'ganjiang_moye',
    name: 'Ganjiang Moye',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.purple,
    assetFileName: 'ganjiang_moye.png',
    starEffects: [
      'Troops HP',
      'Infantry HP',
      'Infantry Attack',
      'Cavalry Attack',
      'Troops Damage Taken Reduction',
    ],
  ),
  ArtifactItemDefinition(
    id: 'gusli',
    name: 'Gusli',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.purple,
    assetFileName: 'gusli.png',
    starEffects: [
      'Reduced Damage Taken from Mages',
      'Troops HP',
      'Troops Attack',
      'Damage Against Angels',
      'Cavalry Attack',
    ],
  ),
  ArtifactItemDefinition(
    id: 'joyeuse',
    name: 'Joyeuse',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.purple,
    assetFileName: 'joyeuse.png',
    starEffects: [
      'Infantry Attack',
      'Army Size Limit',
      'Recruitment Speed',
      'March Speed',
      'Troops Attack',
    ],
  ),
  ArtifactItemDefinition(
    id: 'magic_lamp',
    name: 'Magic Lamp',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.purple,
    assetFileName: 'magic_lamp.png',
    starEffects: [
      'Angel HP',
      'Mage HP',
      'Angel Defense',
      'Troops HP',
      'Angel Attack',
    ],
  ),
  ArtifactItemDefinition(
    id: 'necronomicon',
    name: 'Necronomicon',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.purple,
    assetFileName: 'necronomicon.png',
    starEffects: [
      'Maximum Golems',
      'Golem Attack',
      'Golem HP',
      'Golem Defense',
      'Guardian Conversion',
    ],
  ),

  // Gold Artifacts — maximum 6 stars, level 50.
  ArtifactItemDefinition(
    id: 'angel_sword',
    name: 'Angel Sword',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'angel_sword.png',
    starEffects: [
      'Troops HP',
      'Cavalry Attack',
      'Infantry Attack',
      'Archer Attack',
      'Mage Attack',
      'Angel Limit',
    ],
  ),
  ArtifactItemDefinition(
    id: 'apollo_bow',
    name: "Apollo's Bow",
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'apollo_bow.png',
    starEffects: [
      'Damage Against Cavalry',
      'Archer Attack',
      'Damage Against Angels',
      'Infantry Attack',
      'Cavalry HP',
      'Troops Damage',
    ],
  ),
  ArtifactItemDefinition(
    id: 'athena',
    name: "Athena's Aegis",
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'athena.png',
    starEffects: [
      'Reduced Damage Taken from Archers',
      'Infantry Defense',
      'Infantry HP',
      'Troops HP',
      'Troops Damage Taken Reduction',
      'Infantry Damage Reduction',
    ],
  ),
  ArtifactItemDefinition(
    id: 'brionac',
    name: 'Brionac',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'brionac.png',
    starEffects: [
      'Damage Against Infantry',
      'Mage Attack',
      'Mage HP',
      'Cavalry Attack',
      'Troops Attack',
      'Troops Damage Taken Reduction',
    ],
  ),
  ArtifactItemDefinition(
    id: 'caledfwlch',
    name: 'Caledfwlch',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'caledfwlch.png',
    starEffects: [
      'Reduced Damage Taken from Mages',
      'Damage Against Angels',
      'Cavalry Attack',
      'Troops Attack',
      'Troops HP',
      'Cavalry HP',
    ],
  ),
  ArtifactItemDefinition(
    id: 'cup_of_jamshid',
    name: 'Cup of Jamshid',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'cup_of_jamshid.png',
    starEffects: [
      'Maximum Golems',
      'Golem Attack',
      'Golem HP',
      'Golem Defense',
      'Healing Speed',
      'Troops HP',
    ],
  ),
  ArtifactItemDefinition(
    id: 'emperor_sword',
    name: 'Emperor Sword',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'emperor_sword.png',
    starEffects: [
      'Reduced Damage Taken from Archers',
      'Infantry HP',
      'Infantry Attack',
      'Archer HP',
      'Troops Damage Taken Reduction',
      'Troops Attack',
    ],
  ),
  ArtifactItemDefinition(
    id: 'eye_of_horus',
    name: 'Eye of Horus',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'eye_of_horus.png',
    starEffects: [
      'Reduced Stone Building Cost',
      'Damage Increased When Defending',
      'Reduced Iron Building Cost',
      'Maximum Wounded',
      'Defending Army Defense',
      'Troops HP',
    ],
  ),
  ArtifactItemDefinition(
    id: 'excalibur',
    name: 'Excalibur',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'excalibur.png',
    starEffects: [
      'Troops Attack',
      'Cavalry Attack',
      'Army Size Limit',
      'Infantry Attack',
      'March Speed',
      'Troops Damage',
    ],
  ),
  ArtifactItemDefinition(
    id: 'golden_armor',
    name: 'Golden Armor',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'golden_armor.png',
    starEffects: [
      'Reduced Damage Taken from Mages',
      'Cavalry Defense',
      'Cavalry HP',
      'Troops HP',
      'Cavalry Damage Reduction',
      'Troops Damage Taken Reduction',
    ],
  ),
  ArtifactItemDefinition(
    id: 'heavenly_spear',
    name: 'Heavenly Spear',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'heavenly_spear.png',
    starEffects: [
      'Damage Against Cavalry',
      'Archer HP',
      'Troops Attack',
      'Archer Attack',
      'Troops Damage',
      'Archer Damage',
    ],
  ),
  ArtifactItemDefinition(
    id: 'holy_robe',
    name: 'Holy Robe',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'holy_robe.png',
    starEffects: [
      'Angel HP',
      'Mage HP',
      'Angel Defense',
      'Angel Damage Reduction',
      'Troops HP',
      'Angel Attack',
    ],
  ),
  ArtifactItemDefinition(
    id: 'laevateinn',
    name: 'Laevateinn',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'laevateinn.png',
    starEffects: [
      'Army Size Limit',
      'Troops Attack',
      'Reduced Damage Taken from Mages',
      'Reduced Damage Taken from Archers',
      'Troops Damage',
      'Troops HP',
    ],
  ),
  ArtifactItemDefinition(
    id: 'mjolnir',
    name: 'Mjolnir',
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'mjolnir.png',
    starEffects: [
      'Damage Against Infantry',
      'Infantry Attack',
      'Troops Attack',
      'Mage Attack',
      'Infantry HP',
      'Mage Damage',
    ],
  ),
  ArtifactItemDefinition(
    id: 'trident',
    name: "Poseidon's Trident",
    category: ArtifactCategory.artifact,
    rarity: ArtifactRarity.gold,
    assetFileName: 'trident.png',
    starEffects: [
      'Cross-Realm Attack',
      'Cross-Realm Damage Against Cavalry',
      'Cross-Realm Army Size Limit',
      'Cross-Realm Damage Against Infantry',
      'Cross-Realm Troops HP',
      'Cross-Realm Troops Damage',
    ],
  ),
];
